Update partial icons from the latest upstream version
twbs/blog pull request #438
Opened 2024-03-24 06:37 UTC by XhmikosR

2024-03-24 06:52 UTC, XhmikosR commented
@patrickhlauke could you please take a look? Do we still need `role="img`?

PS. You can check the code diff not the rich diff.

2024-03-24 19:45 UTC, patrickhlauke requested changes
On large screen, the three icon links in the navbar lack an accessible name. Adding `aria-label` to them solves this (see suggested changes)

2024-03-24 19:45 UTC, patrickhlauke commented on src/layouts/partials/navbar.html
>              <a class="nav-link py-2 px-0 px-lg-2" href="{{ .Site.Params.github_org }}" target="_blank" rel="noopener">
```suggestion
            <a class="nav-link py-2 px-0 px-lg-2" href="{{ .Site.Params.github_org }}" target="_blank" rel="noopener" aria-label="GitHub">
```

2024-03-24 19:45 UTC, patrickhlauke commented on src/layouts/partials/navbar.html
>              <a class="nav-link py-2 px-0 px-lg-2" href="https://twitter.com/{{ .Site.Params.twitter }}" target="_blank" rel="noopener">
```suggestion
            <a class="nav-link py-2 px-0 px-lg-2" href="https://twitter.com/{{ .Site.Params.twitter }}" target="_blank" rel="noopener" aria-label="Twitter">
```

2024-03-24 19:45 UTC, patrickhlauke commented on src/layouts/partials/navbar.html
>              <a class="nav-link py-2 px-0 px-lg-2" href="{{ .Site.Params.opencollective }}" target="_blank" rel="noopener">
```suggestion
            <a class="nav-link py-2 px-0 px-lg-2" href="{{ .Site.Params.opencollective }}" target="_blank" rel="noopener" aria-label="Open Collective">
```

2024-03-24 19:46 UTC, patrickhlauke approved these changes

2024-03-24 19:48 UTC, patrickhlauke commented on src/layouts/partials/icons/calendar-event.svg
> -<svg xmlns="http://www.w3.org/2000/svg"{{ with .width }} width="{{ . }}"{{ end }}{{ with .height }} height="{{ . }}"{{ end }}{{ with .class }} class="{{ . }}"{{ end }} viewBox="0 0 16 16" role="img"
it's fine not to have the `role="img"` on these, as without a matching `<title>` or `aria-label="..."` in the `<svg>` it's pointless anyway (and we do provide accessible names separately when these are used)

2024-03-25 07:33 UTC, XhmikosR commented
@patrickhlauke thanks! Can I or can you move your changes to a separate PR?

That way it should be cleaner what we should do in the other repos since this PR is for the icons only :)

2024-03-25 10:48 UTC, patrickhlauke commented
Done https://github.com/twbs/blog/pull/442

2024-03-25 16:27 UTC, merged